[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/home/pi/mediaserver/config/qbittorrent/qBittorrent/data/logs

[BitTorrent]
Session\ExcludedFileNames=
Session\Port=13930
Session\QueueingSystemEnabled=false
Session\SSL\Port=30544

[Core]
AutoDeleteAddedTorrentFile=Never

[Meta]
MigrationVersion=8

[Preferences]
MailNotification\req_auth=true
WebUI\AuthSubnetWhitelist=192.168.68.0/22
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="@ByteArray(6suSzGBgEhmYf8LRGCiWkw==:FRvAWWJobHQhVA0dt87swHxPkx9ygSdVp60LHFG39N+z2BCXaYKM0a50hr3vxI5/1NC7Y+Yg/GEQcWrguGgB0A==)"

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
